excluded:
  - .build
  - DerivedData

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing

line_length:
  warning: 130
  error: 200

identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
